### ISSUE TITLE
Release 0.9.4

### ISSUE THREAD

**Issue by afbjorklund** [Roblox/nomad-driver-containerd#156]
Would it be possible to make a new release, with the support for cgroups v2 included ?

* https://github.com/Roblox/nomad-driver-containerd/pull/133#issuecomment-1159120428

It is blocking the upgrade from Ubuntu 20.04 to Ubuntu 22.04

Since the new release comes with cgroups v2 enabled by default

**Comment by AkihiroSuda** [comment]
@shishir-a412ed Is there ETA of the next release? 🙏

**Comment by shishir-a412ed** [comment]
@AkihiroSuda I will create one today.

**Comment by shishir-a412ed** [comment]
Released [v0.9.4](https://github.com/Roblox/nomad-driver-containerd/releases/tag/v0.9.4)
