### ISSUE TITLE
CPU cgroup quotas are not properly applied

### ISSUE THREAD

**Issue by chuckyz** [Roblox/nomad-driver-containerd#45]
Related to Issue #8 and PR #44,

CPU quotas/periods are currently not properly applied.  Currently the built-in Nomad docker driver has the capability to enable hard CPU limiting via https://www.nomadproject.io/docs/drivers/docker#cpu_hard_limit

There is also special flags around period at https://www.nomadproject.io/docs/drivers/docker#cpu_cfs_period

**Comment by shishir-a412ed** [comment]
After discussing this a bit more internally with @chuckyz , We have decided to **not** expose [`cfs_quota` and `cfs_period`] to the end-user for now.

These are very low-level CPU knobs and could do more harm than good to the end-user.
