### ISSUE TITLE
[question] Is it production ready?

### ISSUE THREAD

**Issue by Oloremo** [Roblox/nomad-driver-containerd#58]
Hello,

I know this question usually have an answer like "it depends" but I wonder what is the current state of this module from your point of view?

Also, I see in Nomad docs what:

> filesystem isolation	none

Does it mean that allocations run with it have full access to underlying fs?

**Comment by shishir-a412ed** [comment]
@Oloremo Thanks for pointing it out! 
Yes, this needs to be changed to [`FSIsolationImage`](https://github.com/hashicorp/nomad/blob/0514e8d3af081cc5a7b106a297b25d6dd16619c5/plugins/drivers/driver.go#L138)

I will test it out, and open a PR with the fix. Feel free to keep the issue `open` until the PR is merged.

To answer your question `[question] Is it production-ready?`

IMO, version `0.6` is definitely production-ready.
We added a lot of stabilization fixes in `0.6` specifically PR #49  and #55. However, there is one issue [`hashicorp/nomad #9750`](https://github.com/hashicorp/nomad/issues/9750) which will go in `hashicorp/nomad` version `1.0.2`. This will affect you if you are launching jobs using `containerd-driver` with a `network` stanza in it. See [`comment`](https://github.com/hashicorp/nomad/issues/9750#issuecomment-756761543) for more details.
