### ISSUE TITLE
Portmap Capabilities + CNI how to use in the driver

### ISSUE THREAD

**Issue by eduardonunesp** [Roblox/nomad-driver-containerd#62]
I just started to test how to use the capabilities by passing the parameters on the job description using cap_add, and I created a CNI network like the following: 

```json
{
  "cniVersion": "0.3.1",
  "name": "mycoolcnichain",
  "plugins": [
     {
        "type": "bridge",
        "isGateway": true,
        "ipMasq": false,
        "bridge": "mybridge",
        "ipam": {
            "type": "host-local",
            "subnet": "10.10.30.0/24",
            "routes": [
                { "dst": "0.0.0.0/0" }
            ],
         "dataDir": "/run/ipam-out-net"
        },
        "dns": {
          "nameservers": [ "8.8.8.8" ]
        }
    },
    {
      "type": "portmap",
      "capabilities": {"portMappings": true},
      "snat": false
    },
}
```

I would like to know how to use the `CAP_ARGS` to specify a port to Redis different from the default Redis port 6379 to 8888, my question is how to pass the `CAP_ARGS` to achieve that option.

CAP_ARGS should be 
```
CAP_ARGS='{"portMappings":[{"hostPort":8888,"containerPort":6379,"protocol":"tcp","hostIP":"127.0.0.1"}]}
```

and job should be:

```
job "redis" {
  datacenters = ["dc1"]

  group "redis-group" {
    task "redis-task" {
      driver = "containerd-driver"

      config {
        image   = "docker.io/library/redis:alpine"
        seccomp = true
        cwd     = "/home/redis"
        cap_add         = ["CAP_ARGS"],
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

**Comment by shishir-a412ed** [comment]
@eduardonunesp  `cap_add` is used for adding Linux capabilities. There is no such capability as `CAP_ARGS` (Reference: https://man7.org/linux/man-pages/man7/capabilities.7.html). 

It looks like `CAP_ARGS` is a CNI environment variable that can be used for setting port mappings.

Did you tried setting `CAP_ARGS` using https://www.nomadproject.io/docs/job-specification/env in the `containerd-driver` nomad job spec, and see if that works?

```
job "redis" {
  datacenters = ["dc1"]

  group "redis-group" {
    task "redis-task" {
      driver = "containerd-driver"
      env {
        CAP_ARGS = \<your_value\>
      }

      config {
        image   = "docker.io/library/redis:alpine"
        seccomp = true
        cwd     = "/home/redis"
      }
      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

**Comment by shishir-a412ed** [comment]
@eduardonunesp Were you able to try this?

**Comment by eduardonunesp** [comment]
Yes it didn't work as expected, but don't worry I'm going to close this question, since I'm focusing on another task

**Comment by shishir-a412ed** [comment]
@eduardonunesp I didn't mean for you to close the issue if it's still unresolved for you 🙂 
Anyways, feel free to reopen whenever you like or when you get a chance to try it out.
