### ISSUE TITLE
[feature request] plugin configuration level privileged mode

### ISSUE THREAD

**Issue by Oloremo** [Roblox/nomad-driver-containerd#73]
Hello!

Currently, it's possible to set the privileged mode in the Nomad job definition via:
```
config {
  privileged = true
}
```

I think it's a security risk. What do you think about making this a plugin-level configuration that will prevent such job configurations?

So it will be:

```
plugin "containerd-driver" {
  config {
    enabled = true
    containerd_runtime = "io.containerd.runc.v2"
    stats_interval = "5s"
    privileged = false
  }
}
```

**Comment by shishir-a412ed** [comment]
@Oloremo 
While I understand the concern, `privileged` is provided as an option in mostly all orchestration systems e.g. k8s or [`nomad docker driver`](https://www.nomadproject.io/docs/drivers/docker#privileged)

It's useful if you want to run `system` jobs that require elevated privileges.
While we cannot remove the `privileged` option (That will break backward compatibility), I don't see a concern with implementing your suggestion.

We can introduce `allow_privileged (default: true)` as a plugin level configuration to override `privileged` at the `TaskConfig` level.

```
plugin "containerd-driver" {
  config {
    enabled = true
    containerd_runtime = "io.containerd.runc.v2"
    stats_interval = "5s"
    allow_privileged = false
  }
}
```

With the above settings, even if someone is launching jobs with `privileged=true`, `containerd-driver` will deny launching the container based on `allow_privileged=false` at the plugin level.

**Comment by Oloremo** [comment]
Oh yes I meant to preserve current behavior, so `allow_privileged = true` by default.

But the ability to disable it on a plugin level would be great.

**Comment by shishir-a412ed** [comment]
@Oloremo 
aah, my bad! Added as a feature request.
