### ISSUE TITLE
Registry authentication

### ISSUE THREAD

**Issue by adeleglise** [Roblox/nomad-driver-containerd#86]
Hi, thanks for opensourcing this plugin.
I try to set it up with a private registry (gitlab), but I need to authenticate before pulling images. As I can see the auth config stanza is not supported.
Am I missing something ? Is it something doable ?

**Comment by shishir-a412ed** [comment]
@adeleglise Yes, the `auth` stanza is currently not implemented. However, It will be implemented in upcoming releases.

Sorry, I don't have a definitive timeline yet. PR's are always welcome :)

**Comment by Oloremo** [comment]
Interested in this as well

**Comment by lisongmin** [comment]
I'm interested but I've been busy lately, so I can't guarantee when I'll finish.

**Comment by shishir-a412ed** [comment]
@lisongmin All good. No commitment necessary. Work on it if/whenever you get a chance.

**Comment by lisongmin** [comment]
Ok, let me have a try.
