### ISSUE TITLE
[feature request] Nomad 1.1+ memory oversubscription support

### ISSUE THREAD

**Issue by Oloremo** [Roblox/nomad-driver-containerd#93]
Hi!

Nomad 1.1 was released today and it comes with a very cool feature of memory oversubscription. You can read about it here:
https://www.hashicorp.com/blog/managing-resources-for-workloads-with-nomad-1-1

They also mention that:
> HashiCorp will help third-party drivers support memory oversubscription.

I wonder if it could be supported in the contained driver.

**Comment by shishir-a412ed** [comment]
@Oloremo This will be addressed in #90 and #91
