### ISSUE TITLE
Unable to build on clean go install

### ISSUE THREAD

**Issue by ncode** [Roblox/nomad-driver-containerd#94]
Hello,

It seems that one of the dependencies is broken and on new go installs the build fails.

```
+ make build
/usr/bin/go build -o containerd-driver .
go: github.com/hashicorp/nomad@v1.1.0 requires
        github.com/hashicorp/go-discover@v0.0.0-20200812215701-c4b85f6ed31f requires
        github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.83: unknown revision v3.0.83
```

I've also added the comment to a bug report on go-discover (https://github.com/hashicorp/go-discover/issues/172)

**Comment by shishir-a412ed** [comment]
@ncode Which version of `go` are you using?

It's working for me on ` go-1.14.3`.

```
# go version
go version go1.14.3 linux/amd64
# nomad version
Nomad v1.1.0 (2678c3604bc9530014208bc167415e167fd440fc)
# make build
/usr/local/go/bin/go build -o containerd-driver .
```

**Comment by shishir-a412ed** [comment]
Just tried this on the latest `go` version as well. Seems to work for me.

```
# go version
go version go1.16.4 linux/amd64
# make build
/usr/local/go/bin/go build -o containerd-driver .
```

**Comment by ncode** [comment]
> Just tried this on the latest `go` version as well. Seems to work for me.
> 
> ```
> # go version
> go version go1.16.4 linux/amd64
> # make build
> /usr/local/go/bin/go build -o containerd-driver .
> ```

it will only fail for a clean install (tencentcloud-dsk-go removed the tag from upstream), but if you have the old tag on your local go path it still works. On my desktop I'm able to build without problems like in your case. On my pipeline to package it fails, because it needs to download everything clean. Tbh, this issue is more of a heads up since go-discover is the one that really needs to fix.

**Comment by shishir-a412ed** [comment]
> > Just tried this on the latest `go` version as well. Seems to work for me.
> > ```
> > # go version
> > go version go1.16.4 linux/amd64
> > # make build
> > /usr/local/go/bin/go build -o containerd-driver .
> > ```
> 
> it will only fail for a clean install (tencentcloud-dsk-go removed the tag from upstream), but if you have the old tag on your local go path it still works. On my desktop I'm able to build without problems like in your case. On my pipeline to package it fails, because it needs to download everything clean. Tbh, this issue is more of a heads up since go-discover is the one that really needs to fix.

@ncode 
So, I was trying it in the vagrant VM which is a clean install (`vagrant destroy` followed by `vagrant up`), However I didn't see it pulling down that tag at all. I also removed the entire contents downloaded under `$GOPATH` and did a clean install, and couldn't reproduce the issue.

Nways, I ll leave the issue open in case someone responds on (hashicorp/go-discover#172)

**Comment by ncode** [comment]
> > > Just tried this on the latest `go` version as well. Seems to work for me.
> > > ```
> > > # go version
> > > go version go1.16.4 linux/amd64
> > > # make build
> > > /usr/local/go/bin/go build -o containerd-driver .
> > > ```
> > 
> > 
> > it will only fail for a clean install (tencentcloud-dsk-go removed the tag from upstream), but if you have the old tag on your local go path it still works. On my desktop I'm able to build without problems like in your case. On my pipeline to package it fails, because it needs to download everything clean. Tbh, this issue is more of a heads up since go-discover is the one that really needs to fix.
> 
> @ncode
> So, I was trying it in the vagrant VM which is a clean install (`vagrant destroy` followed by `vagrant up`), However I didn't see it pulling down that tag at all. I also removed the entire contents downloaded under `$GOPATH` and did a clean install, and couldn't reproduce the issue.
> 
> Nways, I ll leave the issue open in case someone responds on ([hashicorp/go-discover#172](https://github.com/hashicorp/go-discover/issues/172))

Oks. i've tried to reproduce it with multiple systems and as you said it works on ArchLinux, Ubuntu, MacOS and CentOS 7 using go 1.16.4. This issue only happens on CentOS 8 builds. I will dig a bit more to understand why and how :)

**Comment by fagossa** [comment]
@ncode have you tried using `GOPROXY="direct"` ?

**Comment by ncode** [comment]
> @ncode have you tried using `GOPROXY="direct"` ?

That did the trick. It's funny that's only for CentOS tho. But I'm closing since it's not an issue anymore :)
