### ISSUE TITLE
[feature request] Extra hosts in the /etc/hosts 

### ISSUE THREAD

**Issue by Oloremo** [Roblox/nomad-driver-containerd#98]
Hi,

Nomad recently fixed\implement long-standing issue with bridge network Docker workloads not being able to add extra entries into the /etc/hosts.

https://github.com/hashicorp/nomad/pull/10766

I wonder if containerd driver could support this? 

Some applications are dependant on some /etc/hosts entries in our case and we have to do a lot of hacks to workaround it.

**Comment by shishir-a412ed** [comment]
@Oloremo You can add extra hosts to `/etc/hosts` in the container using `extra_hosts` flag. What is missing in `containerd-driver`?

**Comment by Oloremo** [comment]
Ops, I think I assumed it didn't work for all bridged network workloads. Lemme re-check.

**Comment by shishir-a412ed** [comment]
Sure. The important thing here is if you set `host_network` to `true`, you get a copy of host's `/etc/hosts` and `extra_hosts` get added to that. However, if `host_network` is `false`, you start with a default `/etc/hosts` build for the container and `extra_hosts` are added to the default version.

Code link [`here`](https://github.com/Roblox/nomad-driver-containerd/blob/master/containerd/containerd.go#L271-L298)
